#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="7.2.2"
URL="https://www.espocrm.com/downloads/EspoCRM-$VERSION.zip"

dl $URL /usr/local/src
