#!/bin/bash -e
# regenerate EspoCRM secrets

. /etc/default/inithooks

CONF=/var/www/espocrm/data/config.php
PASSWORD=$(mcookie)

sed -i -e "s#\('password' => '\)[^']*'#\1$PASSWORD'#" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user espocrm --pass="$PASSWORD"
