#!/bin/bash -e
# regenerate EspoCRM secrets

. /etc/default/inithooks

SALT=$(mcookie | cut -c1-16)
PASSWORD=$(mcookie)
CONF=/var/www/espocrm/data/config.php

updateconf() {
    sed -i "s|$1.*|$1 => '$2',|;" $CONF
}

updateconf "passwordSalt'" $SALT
updateconf "password'" $PASSWORD
updateconf "cryptKey" $(mcookie)
updateconf "hashSecretKey" $(mcookie)

$INITHOOKS_PATH/bin/mysqlconf.py --user espocrm --pass="$PASSWORD"
