#!/bin/bash -e
# regenerate EspoCRM secrets

. /etc/default/inithooks

SALT=$(mcookie | cut -c1-16)
PASSWORD=$(mcookie)

updateconf() {
    CONF=/var/www/espocrm/data/config.php
    sed -i "s|$1.*|$1 => '$2',|;" $CONF
}

updateconf "passwordSalt'" $SALT
updateconf "password'" $PASSWORD

$INITHOOKS_PATH/bin/mysqlconf.py --user espocrm --pass="$PASSWORD"
